### ISSUE TITLE
find algorithm to manage the queue

### ISSUE THREAD

**Issue by omermad73** [omermad73/lab1#3]

**Comment by DoctorB-CA** [comment]
def sending_l2_messgae(self, timeline, dest_host, l2_message):
        # sending the message
        dest_id = dest_host.id
        time = 3  # "-1" - idk how calc this shit ------------------------------------- need to be fix ---------------
        event = Event(time, "message", self.id, dest_id, l2_message.id)
        timeline.add_event(event)

" time = 3  # "-1" - idk how calc this shit ------------------------------------- need to be fix ---------------"

enter here the solution of the approximation of the time

**Comment by DoctorB-CA** [comment]
p.s. 
time = 3. its random nmber i entered.

in our code there is -1 in some places. think of it as a null. (there is a null in python, but i wanted there will be a num)

**Comment by DoctorB-CA** [comment]
time = timeline.events[0].scheduled_time + 11.4321  # "-1" - idk how calc this shit ------------------------------------- need to be fix ---------------
        event = Event(time, "message received", self.id, dest_id, l2_message.id)
        timeline.add_event(event)



now its the current time + fixed number
